### ISSUE TITLE
"Creating a New Wiki" Form Down - New Workflow?

### ISSUE THREAD

**Issue by cjeller1592** [paul90/wiki-client-dat-variant#2]
I noticed that the form on the "Creating a New Wiki" page is down. Will it be up later or is there a better workflow available to creating one? 

I just copied the empty wiki, made myself the owner in the wiki.json file, and replaced the favicon with one in a local version of SFW I am running. Seems like it works to me: dat://cj-fedwiki.hashbase.io/

Just wanted to be sure. Much thanks to everyone for lowering the barrier of entry to use awesome software like SFW on Dat!

**Comment by paul90** [comment]
Making an editable copy of the empty wiki is a reasonable fallback - it was the documented way of doing it before I wrote the plug-in behind the create new wiki form.

I have also noticed that replication has been problematic recently, but this is a know issue along with the periodic freezes that Beaker is experiencing.

You might find forcing the dat for the client, plugin, and empty wiki to download by seeding them, even if only until they are 100% downloaded, should help. 

I have seen Beaker take a long time to start downloading, and this might be part of why the Creating a New Wiki is not working.

**Comment by cjeller1592** [comment]
The seeding worked like a charm and the form showed up.

I have some friends interested in creating wikis of their own, so I will send them over to the form. They would need to seed the form also, correct? Could I instead create wikis for them through the form, host them on my hashbase, and give them the url?

Thanks for your help Paul!

**Comment by paul90** [comment]
The seeding can take a little while - there are two persistent persistent peers, hashbase and my own server, which should help. I'm in two minds about using the experimental API to add the necessary dat to a user's library.

For your friends, they will need to create their own wiki - as only site creator has write permission. Multi-writer is slowly coming to Beaker, sometime later this year I think.

If they pass you the name, public key, you could host them on hashbase. If you give them a name, they will get rehosted over https, so will be visible to the wider federation.

The latest update to the client, and empty wiki, has modified the wiki client loading and will give a http cover page rather than the previous nearly blank page. There will be a script to update existing wiki dat to the new loader later, once I've finished checking all the plugins.

**Comment by cjeller1592** [comment]
That makes sense. I'll make sure they go through the form themselves until multi-writer functionality comes along. It also might be better for them to get their own Hashbase accounts for future projects anyways. The 100MB for free is good to start.

Thanks again for all your help Paul. Is there a better way to contact you about the Dat wiki other than creating issues? I have been playing around with it in Python and would love to bounce some ideas and questions off you.

**Comment by paul90** [comment]
I can usually be found in the Federated Wiki room on matrix, https://matrix.to/#/#fedwiki:matrix.org

**Comment by cjeller1592** [comment]
Wonderful, thanks again for all your help Paul!
